spring:
   profiles: test
   application:
      name: demoservice
server:
   port: 9090

---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9000

---
spring: 
   profiles: prod
   application:
      name: demoservice
server: 
   port: 443
   ssl:
      key-store: keystore.p12
      key-store-password: springboot
      keyStoreType: PKCS12
      keyAlias: tomcat